"""Unified Routed Mixer reference semantics."""

from .backend import Backend, BackendRegistry, BackendResult
from .ir import (
    BalanceStrategy,
    CapacityPolicy,
    CollisionPolicy,
    DecayGranularity,
    Domain,
    EditGateKind,
    ExpertFunction,
    ExpertRoutingSpec,
    ExpertScoreKind,
    ExpertSelection,
    MixerSpec,
    MutationKind,
    Normalization,
    RecurrentAlgorithm,
    RecurrentSpec,
    Residency,
    RoutingKind,
    ScanMode,
    ScoreActivation,
    SelectionGranularity,
    SelectionScope,
    SparseAttentionSpec,
    SparseIndexerKind,
    StateLayout,
)
from .reference import ReferenceResult, execute, merge_writes
from .routed_reduction import (
    DeviceType,
    RoutedReductionRegistry,
    RoutedReductionResult,
    RoutedReductionSignature,
    ScalarType,
    SupportStatus,
    TensorLayout,
    TensorMetadata,
)

__all__ = [
    "Backend",
    "BackendRegistry",
    "BackendResult",
    "BalanceStrategy",
    "CapacityPolicy",
    "CollisionPolicy",
    "DecayGranularity",
    "DeviceType",
    "Domain",
    "EditGateKind",
    "ExpertFunction",
    "ExpertRoutingSpec",
    "ExpertScoreKind",
    "ExpertSelection",
    "MixerSpec",
    "MutationKind",
    "Normalization",
    "RecurrentAlgorithm",
    "RecurrentSpec",
    "ReferenceResult",
    "Residency",
    "RoutedReductionRegistry",
    "RoutedReductionResult",
    "RoutedReductionSignature",
    "RoutingKind",
    "ScalarType",
    "ScanMode",
    "ScoreActivation",
    "SelectionGranularity",
    "SelectionScope",
    "SparseAttentionSpec",
    "SparseIndexerKind",
    "StateLayout",
    "SupportStatus",
    "TensorLayout",
    "TensorMetadata",
    "execute",
    "merge_writes",
]
